Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np
def func():
    a=[] 
    e=[]
    a=int(input("enter the number:"))
    for i in range(a):
        for j in range(a):
            
            d=np.array(j)**i
            e.append(d)
    print("e=",e)
    arr_2d = np.reshape(e, (a,a),order='F')
    print("matrix:\n",arr_2d)

In [2]:
func()

enter the number:7
e= [1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 3, 4, 5, 6, 0, 1, 4, 9, 16, 25, 36, 0, 1, 8, 27, 64, 125, 216, 0, 1, 16, 81, 256, 625, 1296, 0, 1, 32, 243, 1024, 3125, 7776, 0, 1, 64, 729, 4096, 15625, 46656]
matrix:
 [[    1     0     0     0     0     0     0]
 [    1     1     1     1     1     1     1]
 [    1     2     4     8    16    32    64]
 [    1     3     9    27    81   243   729]
 [    1     4    16    64   256  1024  4096]
 [    1     5    25   125   625  3125 15625]
 [    1     6    36   216  1296  7776 46656]]


Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

 Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
import numpy as np
a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [4]:
def func2():
    a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
    n=np.count_nonzero(a)
    y=[]
    print("n:",n)
    k=int(input("enter k:"))
    movavg=n-k+1
    print("mov_avg=",movavg)
    for j in range(movavg):
        y.append(j)
    for i in range(movavg):
            b=(a[i]+a[i+1]+a[i+2])/k
            print(y[i],"=(",a[i],"+",a[i+1],"+",a[i+2],")/3","=",b)

In [5]:
func2()

n: 13
enter k:3
mov_avg= 11
0 =( 3 + 5 + 7 )/3 = 5.0
1 =( 5 + 7 + 2 )/3 = 4.666666666666667
2 =( 7 + 2 + 8 )/3 = 5.666666666666667
3 =( 2 + 8 + 10 )/3 = 6.666666666666667
4 =( 8 + 10 + 11 )/3 = 9.666666666666666
5 =( 10 + 11 + 65 )/3 = 28.666666666666668
6 =( 11 + 65 + 72 )/3 = 49.333333333333336
7 =( 65 + 72 + 81 )/3 = 72.66666666666667
8 =( 72 + 81 + 99 )/3 = 84.0
9 =( 81 + 99 + 100 )/3 = 93.33333333333333
10 =( 99 + 100 + 150 )/3 = 116.33333333333333
